[package]
name = "veilid-examples-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
tokio = {version = "1.39.3", features=["full"]}
veilid-core = { git = "https://gitlab.com/veilid/veilid.git", version = "0.3.4" }
